version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  install:
    desc: Install dependencies
    cmds:
      - npm install

  build:
    desc: Build for production
    cmds:
      - npm run build

  test:
    desc: Run tests in watch mode
    cmds:
      - npm test

  test:run:
    desc: Run tests once
    cmds:
      - npm run test:run

  dev:
    desc: Start development server
    cmds:
      - npm run dev

  typecheck:
    desc: Run TypeScript type checking
    cmds:
      - npm run typecheck

  preview:
    desc: Preview production build
    deps: [build]
    cmds:
      - npm run preview

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist node_modules/.vite

  ci:
    desc: Run full CI pipeline (install, typecheck, test, build)
    cmds:
      - npm ci
      - npm run typecheck
      - npm run test:run
      - npm run build

  act:
    desc: Test GitHub Actions locally with act (upload step fails locally - expected)
    cmds:
      - act push --job build -P ubuntu-latest=catthehacker/ubuntu:act-latest --container-architecture linux/amd64

  act:dry:
    desc: Dry-run GitHub Actions locally (no execution)
    cmds:
      - act push --job build -n --container-architecture linux/amd64
